version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sam_aira1922
      MYSQL_DATABASE: recipes_db
    ports:
      - "3000:3000"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: noribhavika/recipes:latest
    container_name: recipe-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Sam_aira1922
      DB_NAME: recipes_db

volumes:
  mysql-data: